using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EngineersSalary.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddSalaryReportFieldTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE SalaryReportCountries (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(100) NOT NULL, CONSTRAINT FK_SalaryReportCountries_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportCities (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(100) NOT NULL, CONSTRAINT FK_SalaryReportCities_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportDisciplines (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(120) NOT NULL, CONSTRAINT FK_SalaryReportDisciplines_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportYearsOfExperience (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value int NOT NULL, CONSTRAINT FK_SalaryReportYearsOfExperience_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportCompanyTypes (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(120) NOT NULL, CONSTRAINT FK_SalaryReportCompanyTypes_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportWorkModes (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(80) NOT NULL, CONSTRAINT FK_SalaryReportWorkModes_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportCompensations (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Currency nvarchar(8) NOT NULL, MonthlyNetSalary decimal(18,2) NOT NULL, CONSTRAINT FK_SalaryReportCompensations_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportHousing (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(80) NULL, CONSTRAINT FK_SalaryReportHousing_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportTransportation (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(80) NULL, CONSTRAINT FK_SalaryReportTransportation_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportAnnualBonuses (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(80) NULL, CONSTRAINT FK_SalaryReportAnnualBonuses_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportSalaryFairness (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(80) NULL, CONSTRAINT FK_SalaryReportSalaryFairness_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportFieldRecommendations (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(80) NULL, CONSTRAINT FK_SalaryReportFieldRecommendations_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportNegotiationAdvice (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(1000) NULL, CONSTRAINT FK_SalaryReportNegotiationAdvice_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportProfessionalCertificates (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(120) NULL, CONSTRAINT FK_SalaryReportProfessionalCertificates_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportBenefits (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(600) NULL, CONSTRAINT FK_SalaryReportBenefits_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportEducations (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(120) NULL, CONSTRAINT FK_SalaryReportEducations_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportDailyWorkHours (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value decimal(5,2) NULL, CONSTRAINT FK_SalaryReportDailyWorkHours_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportAdditionalDaysOff (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(80) NULL, CONSTRAINT FK_SalaryReportAdditionalDaysOff_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);
                CREATE TABLE SalaryReportNotes (SalaryReportId uniqueidentifier NOT NULL PRIMARY KEY, Value nvarchar(1000) NULL, CONSTRAINT FK_SalaryReportNotes_SalaryReports FOREIGN KEY (SalaryReportId) REFERENCES SalaryReports(Id) ON DELETE CASCADE);

                CREATE INDEX IX_SalaryReportCountries_Value ON SalaryReportCountries(Value);
                CREATE INDEX IX_SalaryReportCities_Value ON SalaryReportCities(Value);
                CREATE INDEX IX_SalaryReportDisciplines_Value ON SalaryReportDisciplines(Value);
                CREATE INDEX IX_SalaryReportCompanyTypes_Value ON SalaryReportCompanyTypes(Value);
                CREATE INDEX IX_SalaryReportCompensations_MonthlyNetSalary ON SalaryReportCompensations(MonthlyNetSalary);

                EXEC('CREATE TRIGGER TR_SalaryReports_SynchronizeFields ON SalaryReports AFTER INSERT, UPDATE AS BEGIN
                    SET NOCOUNT ON;
                    DELETE c FROM SalaryReportCountries c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportCities c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportDisciplines c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportYearsOfExperience c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportCompanyTypes c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportWorkModes c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportCompensations c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportHousing c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportTransportation c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportAnnualBonuses c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportSalaryFairness c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportFieldRecommendations c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportNegotiationAdvice c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportProfessionalCertificates c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportBenefits c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportEducations c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportDailyWorkHours c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportAdditionalDaysOff c INNER JOIN inserted i ON i.Id=c.SalaryReportId; DELETE c FROM SalaryReportNotes c INNER JOIN inserted i ON i.Id=c.SalaryReportId;
                    INSERT SalaryReportCountries SELECT Id,Country FROM inserted; INSERT SalaryReportCities SELECT Id,City FROM inserted; INSERT SalaryReportDisciplines SELECT Id,Discipline FROM inserted; INSERT SalaryReportYearsOfExperience SELECT Id,YearsOfExperience FROM inserted; INSERT SalaryReportCompanyTypes SELECT Id,CompanyType FROM inserted; INSERT SalaryReportWorkModes SELECT Id,WorkMode FROM inserted; INSERT SalaryReportCompensations SELECT Id,Currency,MonthlyNetSalary FROM inserted; INSERT SalaryReportHousing SELECT Id,HousingProvided FROM inserted; INSERT SalaryReportTransportation SELECT Id,TransportationProvided FROM inserted; INSERT SalaryReportAnnualBonuses SELECT Id,AnnualBonus FROM inserted; INSERT SalaryReportSalaryFairness SELECT Id,SalaryFairness FROM inserted; INSERT SalaryReportFieldRecommendations SELECT Id,RecommendField FROM inserted; INSERT SalaryReportNegotiationAdvice SELECT Id,NegotiationAdvice FROM inserted; INSERT SalaryReportProfessionalCertificates SELECT Id,ProfessionalCertificate FROM inserted; INSERT SalaryReportBenefits SELECT Id,Benefits FROM inserted; INSERT SalaryReportEducations SELECT Id,HighestEducation FROM inserted; INSERT SalaryReportDailyWorkHours SELECT Id,DailyWorkHours FROM inserted; INSERT SalaryReportAdditionalDaysOff SELECT Id,ExtraDayOff FROM inserted; INSERT SalaryReportNotes SELECT Id,Notes FROM inserted;
                END');

                EXEC('CREATE VIEW vwSalaryReportReadRows AS SELECT r.Id, d.Value AS Discipline, co.Value AS Country, ci.Value AS City, y.Value AS YearsOfExperience, ct.Value AS CompanyType, wm.Value AS WorkMode, cp.Currency, cp.MonthlyNetSalary, h.Value AS HousingProvided, t.Value AS TransportationProvided, ab.Value AS AnnualBonus, sf.Value AS SalaryFairness, fr.Value AS RecommendField, na.Value AS NegotiationAdvice, pc.Value AS ProfessionalCertificate, b.Value AS Benefits, e.Value AS HighestEducation, dh.Value AS DailyWorkHours, ad.Value AS ExtraDayOff, n.Value AS Notes FROM SalaryReports r INNER JOIN SalaryReportDisciplines d ON d.SalaryReportId=r.Id INNER JOIN SalaryReportCountries co ON co.SalaryReportId=r.Id INNER JOIN SalaryReportCities ci ON ci.SalaryReportId=r.Id INNER JOIN SalaryReportYearsOfExperience y ON y.SalaryReportId=r.Id INNER JOIN SalaryReportCompanyTypes ct ON ct.SalaryReportId=r.Id INNER JOIN SalaryReportWorkModes wm ON wm.SalaryReportId=r.Id INNER JOIN SalaryReportCompensations cp ON cp.SalaryReportId=r.Id LEFT JOIN SalaryReportHousing h ON h.SalaryReportId=r.Id LEFT JOIN SalaryReportTransportation t ON t.SalaryReportId=r.Id LEFT JOIN SalaryReportAnnualBonuses ab ON ab.SalaryReportId=r.Id LEFT JOIN SalaryReportSalaryFairness sf ON sf.SalaryReportId=r.Id LEFT JOIN SalaryReportFieldRecommendations fr ON fr.SalaryReportId=r.Id LEFT JOIN SalaryReportNegotiationAdvice na ON na.SalaryReportId=r.Id LEFT JOIN SalaryReportProfessionalCertificates pc ON pc.SalaryReportId=r.Id LEFT JOIN SalaryReportBenefits b ON b.SalaryReportId=r.Id LEFT JOIN SalaryReportEducations e ON e.SalaryReportId=r.Id LEFT JOIN SalaryReportDailyWorkHours dh ON dh.SalaryReportId=r.Id LEFT JOIN SalaryReportAdditionalDaysOff ad ON ad.SalaryReportId=r.Id LEFT JOIN SalaryReportNotes n ON n.SalaryReportId=r.Id');
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP VIEW vwSalaryReportReadRows; DROP TRIGGER TR_SalaryReports_SynchronizeFields; DROP TABLE SalaryReportNotes, SalaryReportAdditionalDaysOff, SalaryReportDailyWorkHours, SalaryReportEducations, SalaryReportBenefits, SalaryReportProfessionalCertificates, SalaryReportNegotiationAdvice, SalaryReportFieldRecommendations, SalaryReportSalaryFairness, SalaryReportAnnualBonuses, SalaryReportTransportation, SalaryReportHousing, SalaryReportCompensations, SalaryReportWorkModes, SalaryReportCompanyTypes, SalaryReportYearsOfExperience, SalaryReportDisciplines, SalaryReportCities, SalaryReportCountries;");
        }
    }
}
