// <auto-generated />
using System;
using EngineersSalary.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EngineersSalary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EngineersSalaryDbContext))]
    [Migration("20260710154545_NormalizeSalaryReportFieldOwnership")]
    partial class NormalizeSalaryReportFieldOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ReferenceCatalogs", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid?>("ParentValueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("ParentValueId");

                    b.HasIndex("CatalogId", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("ReferenceValues", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateOnly>("SubmittedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("SalaryReports", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FieldCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("ReferenceValueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SalaryReportId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceValueId");

                    b.HasIndex("SalaryReportId", "FieldCode")
                        .IsUnique();

                    b.ToTable("SalaryReportReferences", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExternalRowId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("SalaryReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("SynchronizedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("SalaryReportId");

                    b.HasIndex("SourceName", "ExternalRowId")
                        .IsUnique();

                    b.ToTable("SalaryReportSourceRecords", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceValue", b =>
                {
                    b.HasOne("EngineersSalary.Domain.ReferenceCatalog", "Catalog")
                        .WithMany("Values")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineersSalary.Domain.ReferenceValue", "ParentValue")
                        .WithMany()
                        .HasForeignKey("ParentValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Catalog");

                    b.Navigation("ParentValue");
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReport", b =>
                {
                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "AnnualBonusField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportAnnualBonuses_Value");

                            b1.ToTable("SalaryReportAnnualBonuses", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "BenefitsField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(600)
                                .HasColumnType("nvarchar(600)");

                            b1.HasKey("SalaryReportId");

                            b1.ToTable("SalaryReportBenefits", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "CityField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportCities_Value");

                            b1.ToTable("SalaryReportCities", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "CompanyTypeField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportCompanyTypes_Value");

                            b1.ToTable("SalaryReportCompanyTypes", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "CountryField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportCountries_Value");

                            b1.ToTable("SalaryReportCountries", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "DisciplineField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportDisciplines_Value");

                            b1.ToTable("SalaryReportDisciplines", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "ExtraDayOffField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportAdditionalDaysOff_Value");

                            b1.ToTable("SalaryReportAdditionalDaysOff", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "HighestEducationField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportEducations_Value");

                            b1.ToTable("SalaryReportEducations", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "HousingProvidedField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportHousing_Value");

                            b1.ToTable("SalaryReportHousing", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "NegotiationAdviceField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("SalaryReportId");

                            b1.ToTable("SalaryReportNegotiationAdvice", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "NotesField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.HasKey("SalaryReportId");

                            b1.ToTable("SalaryReportNotes", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "ProfessionalCertificateField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportProfessionalCertificates_Value");

                            b1.ToTable("SalaryReportProfessionalCertificates", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "RecommendFieldValue", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportFieldRecommendations_Value");

                            b1.ToTable("SalaryReportFieldRecommendations", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "SalaryFairnessField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportSalaryFairness_Value");

                            b1.ToTable("SalaryReportSalaryFairness", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "TransportationProvidedField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportTransportation_Value");

                            b1.ToTable("SalaryReportTransportation", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "WorkModeField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportWorkModes_Value");

                            b1.ToTable("SalaryReportWorkModes", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportCompensation", "Compensation", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("nvarchar(8)");

                            b1.Property<decimal>("MonthlyNetSalary")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("MonthlyNetSalary")
                                .HasDatabaseName("IX_SalaryReportCompensations_MonthlyNetSalary");

                            b1.HasIndex("Currency", "MonthlyNetSalary")
                                .HasDatabaseName("IX_SalaryReportCompensations_Currency_MonthlyNetSalary");

                            b1.ToTable("SalaryReportCompensations", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportDecimalValue", "DailyWorkHoursField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal?>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportDailyWorkHours_Value");

                            b1.ToTable("SalaryReportDailyWorkHours", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportIntegerValue", "YearsOfExperienceField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportYearsOfExperience_Value");

                            b1.ToTable("SalaryReportYearsOfExperience", (string)null);

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.Navigation("AnnualBonusField")
                        .IsRequired();

                    b.Navigation("BenefitsField")
                        .IsRequired();

                    b.Navigation("CityField")
                        .IsRequired();

                    b.Navigation("CompanyTypeField")
                        .IsRequired();

                    b.Navigation("Compensation")
                        .IsRequired();

                    b.Navigation("CountryField")
                        .IsRequired();

                    b.Navigation("DailyWorkHoursField")
                        .IsRequired();

                    b.Navigation("DisciplineField")
                        .IsRequired();

                    b.Navigation("ExtraDayOffField")
                        .IsRequired();

                    b.Navigation("HighestEducationField")
                        .IsRequired();

                    b.Navigation("HousingProvidedField")
                        .IsRequired();

                    b.Navigation("NegotiationAdviceField")
                        .IsRequired();

                    b.Navigation("NotesField")
                        .IsRequired();

                    b.Navigation("ProfessionalCertificateField")
                        .IsRequired();

                    b.Navigation("RecommendFieldValue")
                        .IsRequired();

                    b.Navigation("SalaryFairnessField")
                        .IsRequired();

                    b.Navigation("TransportationProvidedField")
                        .IsRequired();

                    b.Navigation("WorkModeField")
                        .IsRequired();

                    b.Navigation("YearsOfExperienceField")
                        .IsRequired();
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportReference", b =>
                {
                    b.HasOne("EngineersSalary.Domain.ReferenceValue", "ReferenceValue")
                        .WithMany()
                        .HasForeignKey("ReferenceValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EngineersSalary.Domain.SalaryReport", "SalaryReport")
                        .WithMany()
                        .HasForeignKey("SalaryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenceValue");

                    b.Navigation("SalaryReport");
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportSourceRecord", b =>
                {
                    b.HasOne("EngineersSalary.Domain.SalaryReport", "SalaryReport")
                        .WithMany()
                        .HasForeignKey("SalaryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryReport");
                });

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceCatalog", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
