import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { PageDesignComponent } from '../../../shared/ui/page-design';

@Component({
  selector: 'feature-salary-reference-about-page',
  standalone: true,
  imports: [RouterLink, PageDesignComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<engineers-salary-reference-page-design title="Engineers Reference" sub="A practical salary reference built from engineer-submitted data" icon="chart" [sharedToolbarShowCustomize]="false"><div page-table class="about-page"><section class="about-page__intro"><span>THE REFERENCE</span><h1>Make the next career decision with better context.</h1><p>Engineers Reference turns anonymous community submissions into a searchable view of the market. Each report is a signal, not a promise, so compare role, experience, location, currency, and working conditions together.</p><div><a routerLink="/salary-reports">Explore reports</a><a routerLink="/submit-report">Submit your report</a></div></section><div class="about-page__grid"><section><strong>01</strong><h2>Contribute honestly</h2><p>Share what you actually received. Company names can remain anonymous.</p></section><section><strong>02</strong><h2>Compare the full package</h2><p>Salary is only one part of the signal. Work mode, benefits, and experience matter.</p></section><section><strong>03</strong><h2>Keep it useful</h2><p>Reports are normalized and published through the reference API for consistent comparison.</p></section></div></div></engineers-salary-reference-page-design>`,
  styles: [`:host{display:flex;flex:1 1 auto;min-width:0;min-height:0}:host ::ng-deep engineers-salary-reference-page-design{display:flex!important;flex:1 1 auto!important;flex-direction:column!important;width:100%!important;min-width:0!important;min-height:0!important}:host ::ng-deep engineers-salary-reference-page-design .table-area{display:flex!important;flex:1 1 auto!important;width:100%!important;min-width:0!important;min-height:0!important;overflow:hidden!important}.about-page{flex:1 1 auto;width:100%;min-width:0;min-height:0;overflow:auto;padding:0;background:rgb(var(--bg));}.about-page__intro{width:100%;padding:28px 32px;border:0;border-bottom:1px solid rgb(var(--border));background:transparent;}.about-page__intro>span,.about-page__grid strong{color:rgb(var(--primary));font-size:10px;font-weight:800;letter-spacing:.1em}.about-page h1{max-width:980px;margin:10px 0 0;font-size:clamp(28px,3vw,44px);line-height:1}.about-page p{max-width:980px;margin:16px 0 0;color:rgb(var(--muted));font-size:14px;line-height:1.7}.about-page__intro div{display:flex;gap:10px;margin-top:24px}.about-page a{display:inline-flex;align-items:center;min-height:36px;padding:0 13px;border:1px solid rgb(var(--border));color:rgb(var(--fg));font-size:12px;text-decoration:none}.about-page a:first-child{border-color:rgb(var(--primary));background:rgb(var(--primary));color:#11130d;font-weight:800}.about-page__grid{display:grid;grid-template-columns:repeat(3,1fr);gap:0;border-bottom:1px solid rgb(var(--border))}.about-page__grid section{padding:24px 32px;border:0;border-right:1px solid rgb(var(--border));background:transparent}.about-page__grid section:last-child{border-right:0}.about-page__grid h2{margin:10px 0 0;font-size:16px}.about-page__grid p{margin-top:8px;font-size:12px}@media(max-width:700px){.about-page__intro,.about-page__grid section{padding:20px}.about-page__grid{grid-template-columns:1fr}.about-page__grid section{border-right:0;border-bottom:1px solid rgb(var(--border))}.about-page__intro div{flex-direction:column}}`]
})
export class SalaryReferenceAboutPageComponent {}
