// <auto-generated />
using System;
using EngineersSalary.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EngineersSalary.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(EngineersSalaryDbContext))]
    partial class EngineersSalaryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ReferenceCatalogs", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid?>("ParentValueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("ParentValueId");

                    b.HasIndex("CatalogId", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("ReferenceValues", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateOnly>("SubmittedAt")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("Status", "SubmittedAt");

                    b.ToTable("SalaryReports", null, t =>
                        {
                            t.HasCheckConstraint("CK_SalaryReports_Status", "\"Status\" IN ('Draft', 'Published', 'Hidden')");
                        });
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FieldCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ReferenceValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalaryReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceValueId");

                    b.HasIndex("SalaryReportId", "FieldCode")
                        .IsUnique();

                    b.ToTable("SalaryReportReferences", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportSourceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalRowId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("SalaryReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("SynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SalaryReportId");

                    b.HasIndex("SourceName", "ExternalRowId")
                        .IsUnique();

                    b.ToTable("SalaryReportSourceRecords", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalarySubmissionIdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SalaryReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SalaryReportId")
                        .IsUnique();

                    b.ToTable("SalarySubmissionIdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceValue", b =>
                {
                    b.HasOne("EngineersSalary.Domain.ReferenceCatalog", "Catalog")
                        .WithMany("Values")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EngineersSalary.Domain.ReferenceValue", "ParentValue")
                        .WithMany()
                        .HasForeignKey("ParentValueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Catalog");

                    b.Navigation("ParentValue");
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReport", b =>
                {
                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "AnnualBonusField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportAnnualBonuses_Value");

                            b1.ToTable("SalaryReportAnnualBonuses", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportAnnualBonuses_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "BenefitsField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(600)
                                .HasColumnType("character varying(600)");

                            b1.HasKey("SalaryReportId");

                            b1.ToTable("SalaryReportBenefits", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportBenefits_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "CityField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportCities_Value");

                            b1.ToTable("SalaryReportCities", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportCities_Value", "\"Value\" IS NOT NULL AND char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "CompanyTypeField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportCompanyTypes_Value");

                            b1.ToTable("SalaryReportCompanyTypes", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportCompanyTypes_Value", "\"Value\" IS NOT NULL AND char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "CountryField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportCountries_Value");

                            b1.ToTable("SalaryReportCountries", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportCountries_Value", "\"Value\" IS NOT NULL AND char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "DisciplineField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportDisciplines_Value");

                            b1.ToTable("SalaryReportDisciplines", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportDisciplines_Value", "\"Value\" IS NOT NULL AND char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "ExtraDayOffField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportAdditionalDaysOff_Value");

                            b1.ToTable("SalaryReportAdditionalDaysOff", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportAdditionalDaysOff_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "HighestEducationField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportEducations_Value");

                            b1.ToTable("SalaryReportEducations", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportEducations_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "HousingProvidedField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportHousing_Value");

                            b1.ToTable("SalaryReportHousing", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportHousing_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "NegotiationAdviceField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("SalaryReportId");

                            b1.ToTable("SalaryReportNegotiationAdvice", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportNegotiationAdvice_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "ProfessionalCertificateField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportProfessionalCertificates_Value");

                            b1.ToTable("SalaryReportProfessionalCertificates", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportProfessionalCertificates_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "RecommendFieldValue", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportFieldRecommendations_Value");

                            b1.ToTable("SalaryReportFieldRecommendations", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportFieldRecommendations_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "SalaryFairnessField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportSalaryFairness_Value");

                            b1.ToTable("SalaryReportSalaryFairness", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportSalaryFairness_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "TransportationProvidedField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportTransportation_Value");

                            b1.ToTable("SalaryReportTransportation", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportTransportation_Value", "\"Value\" IS NULL OR char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportTextValue", "WorkModeField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportWorkModes_Value");

                            b1.ToTable("SalaryReportWorkModes", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportWorkModes_Value", "\"Value\" IS NOT NULL AND char_length(btrim(\"Value\")) > 0");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportCurrencyValue", "CurrencyField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportCurrencies_Value");

                            b1.ToTable("SalaryReportCurrencies", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportCurrencies_Value", "char_length(btrim(\"Value\")) BETWEEN 1 AND 8");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportDecimalValue", "DailyWorkHoursField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Value")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportDailyWorkHours_Value");

                            b1.ToTable("SalaryReportDailyWorkHours", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportDailyWorkHours_Value", "\"Value\" IS NULL OR \"Value\" BETWEEN 0 AND 24");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportIntegerValue", "YearsOfExperienceField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportYearsOfExperience_Value");

                            b1.ToTable("SalaryReportYearsOfExperience", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportYearsOfExperience_Value", "\"Value\" BETWEEN 0 AND 60");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.OwnsOne("EngineersSalary.Domain.SalaryReportMonthlyNetSalaryValue", "MonthlyNetSalaryField", b1 =>
                        {
                            b1.Property<Guid>("SalaryReportId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)");

                            b1.HasKey("SalaryReportId");

                            b1.HasIndex("Value")
                                .HasDatabaseName("IX_SalaryReportMonthlyNetSalaries_Value");

                            b1.ToTable("SalaryReportMonthlyNetSalaries", null, t =>
                                {
                                    t.HasCheckConstraint("CK_SalaryReportMonthlyNetSalaries_Value", "\"Value\" > 0 AND \"Value\" <= 10000000");
                                });

                            b1.WithOwner("SalaryReport")
                                .HasForeignKey("SalaryReportId");

                            b1.Navigation("SalaryReport");
                        });

                    b.Navigation("AnnualBonusField")
                        .IsRequired();

                    b.Navigation("BenefitsField")
                        .IsRequired();

                    b.Navigation("CityField")
                        .IsRequired();

                    b.Navigation("CompanyTypeField")
                        .IsRequired();

                    b.Navigation("CountryField")
                        .IsRequired();

                    b.Navigation("CurrencyField")
                        .IsRequired();

                    b.Navigation("DailyWorkHoursField")
                        .IsRequired();

                    b.Navigation("DisciplineField")
                        .IsRequired();

                    b.Navigation("ExtraDayOffField")
                        .IsRequired();

                    b.Navigation("HighestEducationField")
                        .IsRequired();

                    b.Navigation("HousingProvidedField")
                        .IsRequired();

                    b.Navigation("MonthlyNetSalaryField")
                        .IsRequired();

                    b.Navigation("NegotiationAdviceField")
                        .IsRequired();

                    b.Navigation("ProfessionalCertificateField")
                        .IsRequired();

                    b.Navigation("RecommendFieldValue")
                        .IsRequired();

                    b.Navigation("SalaryFairnessField")
                        .IsRequired();

                    b.Navigation("TransportationProvidedField")
                        .IsRequired();

                    b.Navigation("WorkModeField")
                        .IsRequired();

                    b.Navigation("YearsOfExperienceField")
                        .IsRequired();
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportReference", b =>
                {
                    b.HasOne("EngineersSalary.Domain.ReferenceValue", "ReferenceValue")
                        .WithMany()
                        .HasForeignKey("ReferenceValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EngineersSalary.Domain.SalaryReport", "SalaryReport")
                        .WithMany()
                        .HasForeignKey("SalaryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenceValue");

                    b.Navigation("SalaryReport");
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalaryReportSourceRecord", b =>
                {
                    b.HasOne("EngineersSalary.Domain.SalaryReport", "SalaryReport")
                        .WithMany()
                        .HasForeignKey("SalaryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryReport");
                });

            modelBuilder.Entity("EngineersSalary.Domain.SalarySubmissionIdempotencyRecord", b =>
                {
                    b.HasOne("EngineersSalary.Domain.SalaryReport", "SalaryReport")
                        .WithOne()
                        .HasForeignKey("EngineersSalary.Domain.SalarySubmissionIdempotencyRecord", "SalaryReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalaryReport");
                });

            modelBuilder.Entity("EngineersSalary.Domain.ReferenceCatalog", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
